# Generated by Django 4.2.3 on 2023-07-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_comment_post_comment_user_contact_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
